var express = require('express');
var router = express.Router();
var pistas = require('../controllers/pistaController');
var evento = require('../controllers/eventoController');
var users = require('../controllers/userController');
console.log('inicio de rotas pistas');
router.get('/', pistas.index);
router.get('/cadastrar', pistas.cadastrar);
router.get('/editar:pista', pistas.editar);
router.get('/buscar:id', pistas.buscar);
console.log('finm de totas pistas');
console.log('inicio de rotas eventos');
router.get('/evento', evento.index);
router.get('/evento/cadastrar', evento.cadastrar);
router.get('/evento/editar:evento', evento.editar);
router.get('/evento/buscar:id', evento.buscar);
console.log('finm de totas eventos');
console.log('inicio de rotas usuario');
router.get('/user', users.index);
router.get('/user/cadastrar', users.cadastrar);
router.get('/user/editar:pista', users.editar);
router.get('/user/buscar:id', users.buscar);
console.log('fim de totas usuario');
module.exports = router;
console.log('fim de configuracoes de rotas');
